### ISSUE TITLE
Stdio stty

### ISSUE THREAD

**Issue by mushishi78** [ninefold/cli#17]
Stdio#ask and #read_key seem to be using stty, which isn't compatible with Windows. It be cool if you change to something more universal.

**Comment by MadRabbit** [comment]
Hi Max,  thanks for the ticket and the pull requests you've created.

Basically, we don't support windows in the CLI at this point, it's a very small group of users and we wanted to make it right and think it through before we go there. At this moment we decided to focus on the unix implementation only.

**Comment by mushishi78** [comment]
No worries :)

**Comment by ezekg** [comment]
Just chiming in here. I've been building a CLI app and I found that the code below works perfectly on Windows using Ruby >= 1.9.3 (I'm guessing it does some fancy low level stuff).

```ruby
def read_key
  $stdin.noecho do |io|
    io.raw!

    key = io.getc.chr

    if key == "\e"
      key << io.getc.chr rescue nil
      key << io.getc.chr rescue nil
    end

    io.cooked!

    key
  end
end
```

**Comment by MadRabbit** [comment]
@ezekg hey thanks for the example, unfortunately that is a ruby 1.9 feature and when we were designing this thing we were aiming to support 1.8 as well. hence all the hacks

**Comment by ezekg** [comment]
Gotcha. I haven't actively been testing that far back. Good to know.
